CREATE TABLE Crime.Staging_Table(
	StagingID VARCHAR(200) NOT NULL,
	ARREST_KEY VARCHAR(200) NULL,
	ARREST_DATE VARCHAR(200) NULL,
	PD_CD VARCHAR(200) NULL,
	PD_DESC VARCHAR(200) NULL,
	KY_CD VARCHAR(200) NULL,
	OFNS_DESC VARCHAR(200) NULL,
	LAW_CODE VARCHAR(200) NULL,
	LAW_CAT_CD VARCHAR(50) NULL,
	ARREST_BORO VARCHAR(50) NULL,
	ARREST_PRECINCT VARCHAR(200) NULL,
	JURISDICTION_CODE VARCHAR(200) NULL,
	AGE_GROUP VARCHAR(200)NULL,
	PREP_RACE VARCHAR(200)NULL,
	X_COORD_CD VARCHAR(200) NULL,
	Y_COORD_CD VARCHAR(200) NULL,
	Latitude VARCHAR(100) NULL,
	Longitude VARCHAR(100) NULL
	PRIMARY KEY(StagingID)

	);

